# Exercise the shipped executable and parse every JSON line with CMake's JSON parser.
if(NOT DEFINED AIRTRACE OR NOT DEFINED FIXTURES OR NOT DEFINED WORK)
    message(FATAL_ERROR "AIRTRACE, FIXTURES, and WORK are required")
endif()

foreach(capture IN ITEMS wpa-Induction Network_Join_Nokia_Mobile)
    if(capture STREQUAL "wpa-Induction")
        set(expected 1093)
        set(expected_parsed 1083)
        set(expected_errors 10)
        set(expected_result 1)
        set(invalid_frames 21 43 574 607 623 681 692 752 1005 1074)
    else()
        set(expected 1180)
        set(expected_parsed 1180)
        set(expected_errors 0)
        set(expected_result 0)
        set(invalid_frames "")
    endif()
    execute_process(COMMAND "${AIRTRACE}" parse "${FIXTURES}/${capture}.pcap" --jsonl --stats
        RESULT_VARIABLE result OUTPUT_VARIABLE jsonl ERROR_VARIABLE summary)
    if(NOT result EQUAL expected_result)
        message(FATAL_ERROR "${capture}: ${result}: ${summary}")
    endif()
    # Escape list separators before converting the physical JSONL lines to a list.
    string(REPLACE ";" "\\;" jsonl "${jsonl}")
    string(REGEX REPLACE "\n$" "" jsonl "${jsonl}")
    string(REPLACE "\n" ";" lines "${jsonl}")
    list(LENGTH lines actual)
    if(NOT actual EQUAL expected)
        message(FATAL_ERROR "${capture}: expected ${expected} lines, got ${actual}")
    endif()
    set(index 0)
    set(diagnostics "")
    foreach(line IN LISTS lines)
        math(EXPR index "${index} + 1")
        string(JSON number GET "${line}" frame)
        string(JSON timestamp GET "${line}" ts)
        list(FIND invalid_frames "${index}" invalid_index)
        if(NOT invalid_index EQUAL -1)
            string(JSON error GET "${line}" error)
            if(NOT error STREQUAL "unsupported format" OR NOT number EQUAL index)
                message(FATAL_ERROR "Wrong diagnostic at frame ${index}: ${line}")
            endif()
            string(APPEND diagnostics "Frame ${index}: unsupported format\n")
            continue()
        endif()
        string(JSON type GET "${line}" type)
        string(JSON subtype GET "${line}" subtype)
        string(JSON ie_count LENGTH "${line}" ie_summary)
        if(NOT number EQUAL index OR NOT timestamp GREATER 0 OR type STREQUAL "" OR subtype STREQUAL "")
            message(FATAL_ERROR "${capture}: invalid record ${index}")
        endif()
        if(capture STREQUAL "wpa-Induction")
            set(handshake_frames 87 89 92 94)
            list(FIND handshake_frames "${index}" handshake_index)
            if(NOT handshake_index EQUAL -1)
                string(JSON msg GET "${line}" eapol_msg)
                math(EXPR expected_msg "${handshake_index} + 1")
                if(NOT msg EQUAL expected_msg)
                    message(FATAL_ERROR "Wrong EAPOL classification at ${index}")
                endif()
            endif()
        endif()
    endforeach()
    if(NOT summary MATCHES "Frames: ${expected}  parsed: ${expected_parsed}  errors: ${expected_errors}")
        message(FATAL_ERROR "${capture}: incorrect summary: ${summary}")
    endif()
    if(capture STREQUAL "wpa-Induction" AND NOT summary MATCHES
       "client=00:0d:93:82:36:3a bssid=00:0c:41:82:b2:55 observed=1234 complete=yes counts=1,1,1,1")
        message(FATAL_ERROR "Handshake summary missing: ${summary}")
    endif()
    execute_process(COMMAND "${AIRTRACE}" parse "${FIXTURES}/${capture}.pcap" --stats
        RESULT_VARIABLE result OUTPUT_VARIABLE stats_only ERROR_VARIABLE errors)
    set(combined "${diagnostics}${stats_only}")
    if(NOT result EQUAL expected_result OR NOT combined STREQUAL summary OR NOT errors STREQUAL diagnostics)
        message(FATAL_ERROR "--stats output routing failed for ${capture}")
    endif()
endforeach()

execute_process(COMMAND "${AIRTRACE}" parse "${FIXTURES}/Network_Join_Nokia_Mobile.pcap"
    RESULT_VARIABLE result OUTPUT_VARIABLE default_output ERROR_VARIABLE errors)
execute_process(COMMAND "${AIRTRACE}" parse "${FIXTURES}/Network_Join_Nokia_Mobile.pcap" --jsonl
    RESULT_VARIABLE explicit_result OUTPUT_VARIABLE explicit_output ERROR_VARIABLE explicit_errors)
if(NOT result EQUAL 0 OR NOT explicit_result EQUAL 0 OR NOT default_output STREQUAL explicit_output
   OR NOT errors STREQUAL "" OR NOT explicit_errors STREQUAL "")
    message(FATAL_ERROR "Default output must equal explicit --jsonl output")
endif()

execute_process(COMMAND "${AIRTRACE}" --version RESULT_VARIABLE result OUTPUT_VARIABLE version)
if(NOT result EQUAL 0 OR NOT version STREQUAL "airtrace 0.1.0\n")
    message(FATAL_ERROR "Version output mismatch: ${version}")
endif()
execute_process(COMMAND "${AIRTRACE}" parse "${FIXTURES}/wpa-Induction.pcap" --bogus
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 2 OR NOT output STREQUAL "" OR NOT errors MATCHES "Unknown option")
    message(FATAL_ERROR "Unknown options must fail with exit 2")
endif()
file(WRITE "${WORK}/invalid-input.pcap" "not a pcap")
execute_process(COMMAND "${AIRTRACE}" parse "${WORK}/invalid-input.pcap"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 1 OR NOT output STREQUAL "" OR errors STREQUAL "")
    message(FATAL_ERROR "Malformed input must fail with diagnostic")
endif()
message(STATUS "CLI: 2273 JSON records, both summaries, handshake, version and error paths verified")
